# Generated by Django 4.2.13 on 2024-06-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_device_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="image",
            field=models.ImageField(null=True, upload_to="photos/"),
        ),
    ]
