# Generated by Django 4.2.13 on 2024-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_borrow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="borrow_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
