# Generated by Django 4.2.13 on 2024-06-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_alter_borrow_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="borrow_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
