# Generated by Django 4.2.13 on 2024-06-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0009_alter_borrow_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
