# Generated by Django 4.2.13 on 2024-06-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0012_device_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="admin",
            field=models.BooleanField(default=0),
        ),
    ]
