# Generated by Django 4.2.13 on 2024-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0014_borrow_tmp_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="phone",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="real_name",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="sex",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="admin",
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
