# Generated by Django 4.2.13 on 2024-06-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0015_userinfo_phone_userinfo_real_name_userinfo_sex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
