# Generated by Django 4.2.13 on 2024-06-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0016_userinfo_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
